import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(undefined);

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.services': 'Services',
    'nav.products': 'Products',
    'nav.documents': 'Documents',
    'nav.whatDocs': 'What Docs I Need',
    'nav.reclamation': 'Reclamation',
    'nav.logout': 'Logout',
    'nav.studentNetwork': 'Student Network',
    'nav.profile': 'Profile',
    
    // Login Page
    'login.title': 'Stucial',
    'login.subtitle': 'Morocco\'s premier social platform connecting university students',
    'login.welcomeBack': 'Welcome back!',
    'login.signInMessage': 'Sign in to connect with students across Morocco',
    'login.email': 'University Email',
    'login.password': 'Password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.signIn': 'Sign In',
    'login.noAccount': 'Don\'t have an account?',
    'login.register': 'Register here',
    'login.footer': '© 2025 Stucial. For Moroccan University Students.',
    
    // Dashboard
    'dashboard.trending': 'Trending Now',
    'dashboard.whatsMind': 'What\'s on your mind?',
    'dashboard.addImage': 'Add image URL (optional)',
    'dashboard.post': 'Post',
    'dashboard.share': 'Share',
    'dashboard.sharePost': 'Share Post',
    'dashboard.shareWithFriends': 'Share with Friends',
    'dashboard.copyLink': 'Copy Link',
    'dashboard.writeComment': 'Write a comment...',
    'dashboard.justNow': 'Just now',
    'dashboard.createPost': 'Create Post',
    'dashboard.writePost': 'Write your post...',
    'dashboard.uploadImage': 'Upload Image',
    'dashboard.publish': 'Publish',
    'dashboard.delete': 'Delete',
    'dashboard.cancel': 'Cancel',
    'dashboard.hideMessages': 'Hide Messages',
    'dashboard.showMessages': 'Show Messages',
    'dashboard.publishComment': 'Publish',
    'dashboard.selectFriend': 'Select a friend to share with',
    
    // Services Page
    'services.title': 'Student Services',
    'services.subtitle': 'Discover services offered by fellow students to help with your academic journey',
    'services.filterServices': 'Filter Services',
    'services.university': 'University',
    'services.city': 'City',
    'services.allUniversities': 'All Universities',
    'services.allCities': 'All Cities',
    'services.showing': 'Showing',
    'services.of': 'of',
    'services.servicesText': 'services',
    'services.reviews': 'reviews',
    'services.comment': 'Comment',
    'services.chat': 'Chat',
    'services.chatWith': 'Chat with',
    'services.typeMessage': 'Type your message here...',
    'services.sendMessage': 'Send Message',
    'services.addService': 'Add Service',
    'services.title': 'Service Title',
    'services.description': 'Service Description',
    'services.images': 'Service Images',
    'services.price': 'Price',
    'services.category': 'Category',
    'services.portfolio': 'Portfolio Link',
    'services.skills': 'Skills (optional)',
    'services.experience': 'Years of Experience (optional)',
    'services.projects': 'Number of Projects (optional)',
    'services.publishService': 'Publish Service',
    'services.rating': 'Rating',
    'services.writeReview': 'Write your review...',
    'services.submitReview': 'Submit Review',
    'services.viewReviews': 'View Reviews',
    'services.rateService': 'Rate this service',
    
    // Products Page
    'products.title': 'Academic Products',
    'products.subtitle': 'Browse materials, notes, and resources shared by students',
    'products.filterProducts': 'Filter Products',
    'products.showing': 'Showing',
    'products.of': 'of',
    'products.productsText': 'products',
    'products.viewDetails': 'View Details',
    'products.description': 'Description',
    'products.seller': 'Seller',
    'products.views': 'Views',
    'products.contactSeller': 'Contact Seller',
    'products.addYourProduct': 'Add Your Product',
    'products.addProduct': 'Add Product',
    'products.productTitle': 'Product Title',
    'products.productDescription': 'Product Description',
    'products.price': 'Price',
    'products.category': 'Category',
    'products.condition': 'Condition',
    'products.imageUrl': 'Image URL',
    'products.publish': 'Publish Product',
    'products.selectCategory': 'Select category',
    'products.selectCondition': 'Select condition',
    'products.likeNew': 'Like New',
    'products.used': 'Used - Good',
    'products.digital': 'Digital',
    
    // Documents Page
    'documents.title': 'Document Library',
    'documents.subtitle': 'Access shared courses, notes, exercises, and exam materials',
    'documents.search': 'Search documents...',
    'documents.filterSubject': 'Filter by subject',
    'documents.filterType': 'Filter by type',
    'documents.allSubjects': 'All Subjects',
    'documents.allTypes': 'All Types',
    'documents.showing': 'Showing',
    'documents.of': 'of',
    'documents.documentsText': 'documents',
    'documents.uploadedBy': 'Uploaded by',
    'documents.downloads': 'downloads',
    'documents.download': 'Download',
    
    // What Docs I Need Page
    'whatDocs.title': 'What Documents Do I Need?',
    'whatDocs.subtitle': 'Complete guide to required documents for various administrative procedures',
    'whatDocs.processingTime': 'Processing time:',
    'whatDocs.requiredDocs': 'Required Documents:',
    'whatDocs.downloadTemplate': 'Download',
    'whatDocs.generalTips': 'General Tips',
    'whatDocs.searchDocs': 'Search for documents...',
    
    // Reclamation Page
    'reclamation.title': 'Submit a Reclamation',
    'reclamation.subtitle': 'Have an issue or concern? Let us know and we\'ll help you resolve it',
    'reclamation.success': 'Your reclamation has been submitted successfully! Our support team will review it within 24-48 hours.',
    'reclamation.category': 'Category',
    'reclamation.selectCategory': 'Select a category',
    'reclamation.subject': 'Subject',
    'reclamation.subjectPlaceholder': 'Brief summary of your issue',
    'reclamation.description': 'Description',
    'reclamation.descriptionPlaceholder': 'Please provide detailed information about your reclamation...',
    'reclamation.descriptionHelp': 'Be as specific as possible to help us resolve your issue quickly',
    'reclamation.yourEmail': 'Your Email',
    'reclamation.emailPlaceholder': 'your.email@university.ma',
    'reclamation.attachment': 'Attachment (Optional)',
    'reclamation.uploadFile': 'Click to upload a file (PDF, Image, or Document)',
    'reclamation.responseTime': 'Please note: Response time is typically 24-48 hours. For urgent matters, please visit the student affairs office directly.',
    'reclamation.submit': 'Submit Reclamation',
    'reclamation.emailSupport': 'Email Support',
    'reclamation.forGeneralInquiries': 'For general inquiries',
    
    // Chat Panel
    'chat.messages': 'Messages',
    'chat.searchMessages': 'Search messages...',
    'chat.online': 'Online',
    'chat.typeMessage': 'Type a message...',
    
    // Common
    'common.all': 'All',
    
    // Profile Page
    'profile.title': 'My Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.university': 'University',
    'profile.city': 'City',
    'profile.bio': 'Bio',
    'profile.joinedDate': 'Joined',
    'profile.myPosts': 'My Posts',
    'profile.myServices': 'My Services',
    'profile.myProducts': 'My Products',
    'profile.saveChanges': 'Save Changes',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.services': 'Services',
    'nav.products': 'Produits',
    'nav.documents': 'Documents',
    'nav.whatDocs': 'Quels documents?',
    'nav.reclamation': 'Réclamation',
    'nav.logout': 'Déconnexion',
    'nav.studentNetwork': 'Réseau étudiant',
    'nav.profile': 'Profil',
    
    // Login Page
    'login.title': 'Stucial',
    'login.subtitle': 'La plateforme sociale de référence pour connecter les étudiants universitaires marocains',
    'login.welcomeBack': 'Bon retour!',
    'login.signInMessage': 'Connectez-vous pour échanger avec les étudiants à travers le Maroc',
    'login.email': 'Email universitaire',
    'login.password': 'Mot de passe',
    'login.rememberMe': 'Se souvenir de moi',
    'login.forgotPassword': 'Mot de passe oublié?',
    'login.signIn': 'Se connecter',
    'login.noAccount': 'Pas de compte?',
    'login.register': 'S\'inscrire ici',
    'login.footer': '© 2025 Stucial. Pour les étudiants universitaires marocains.',
    
    // Dashboard
    'dashboard.trending': 'Tendances actuelles',
    'dashboard.whatsMind': 'Quoi de neuf?',
    'dashboard.addImage': 'Ajouter une URL d\'image (optionnel)',
    'dashboard.post': 'Publier',
    'dashboard.share': 'Partager',
    'dashboard.sharePost': 'Partager la publication',
    'dashboard.shareWithFriends': 'Partager avec des amis',
    'dashboard.copyLink': 'Copier le lien',
    'dashboard.writeComment': 'Écrire un commentaire...',
    'dashboard.justNow': 'À l\'instant',
    'dashboard.createPost': 'Créer une publication',
    'dashboard.writePost': 'Écrivez votre publication...',
    'dashboard.uploadImage': 'Télécharger une image',
    'dashboard.publish': 'Publier',
    'dashboard.delete': 'Supprimer',
    'dashboard.cancel': 'Annuler',
    'dashboard.hideMessages': 'Masquer les messages',
    'dashboard.showMessages': 'Afficher les messages',
    'dashboard.publishComment': 'Publier',
    'dashboard.selectFriend': 'Sélectionnez un ami pour partager',
    
    // Services Page
    'services.title': 'Services étudiants',
    'services.subtitle': 'Découvrez les services proposés par vos camarades pour vous aider dans votre parcours académique',
    'services.filterServices': 'Filtrer les services',
    'services.university': 'Université',
    'services.city': 'Ville',
    'services.allUniversities': 'Toutes les universités',
    'services.allCities': 'Toutes les villes',
    'services.showing': 'Affichage de',
    'services.of': 'sur',
    'services.servicesText': 'services',
    'services.reviews': 'avis',
    'services.comment': 'Commenter',
    'services.chat': 'Discuter',
    'services.chatWith': 'Discuter avec',
    'services.typeMessage': 'Tapez votre message ici...',
    'services.sendMessage': 'Envoyer le message',
    'services.addService': 'Ajouter un service',
    'services.title': 'Titre du service',
    'services.description': 'Description du service',
    'services.images': 'Images du service',
    'services.price': 'Prix',
    'services.category': 'Catégorie',
    'services.portfolio': 'Lien du portfolio',
    'services.skills': 'Compétences (optionnel)',
    'services.experience': 'Années d\'expérience (optionnel)',
    'services.projects': 'Nombre de projets (optionnel)',
    'services.publishService': 'Publier le service',
    'services.rating': 'Évaluation',
    'services.writeReview': 'Écrivez votre avis...',
    'services.submitReview': 'Soumettre l\'avis',
    'services.viewReviews': 'Voir les avis',
    'services.rateService': 'Évaluer ce service',
    
    // Products Page
    'products.title': 'Produits académiques',
    'products.subtitle': 'Parcourez les supports, notes et ressources partagées par les étudiants',
    'products.filterProducts': 'Filtrer les produits',
    'products.showing': 'Affichage de',
    'products.of': 'sur',
    'products.productsText': 'produits',
    'products.viewDetails': 'Voir les détails',
    'products.description': 'Description',
    'products.seller': 'Vendeur',
    'products.views': 'Vues',
    'products.contactSeller': 'Contacter le vendeur',
    'products.addYourProduct': 'Ajouter votre produit',
    'products.addProduct': 'Ajouter un produit',
    'products.productTitle': 'Titre du produit',
    'products.productDescription': 'Description du produit',
    'products.price': 'Prix',
    'products.category': 'Catégorie',
    'products.condition': 'État',
    'products.imageUrl': 'URL de l\'image',
    'products.publish': 'Publier le produit',
    'products.selectCategory': 'Sélectionner une catégorie',
    'products.selectCondition': 'Sélectionner un état',
    'products.likeNew': 'Comme neuf',
    'products.used': 'Utilisé - Bon état',
    'products.digital': 'Numérique',
    
    // Documents Page
    'documents.title': 'Bibliothèque de documents',
    'documents.subtitle': 'Accédez aux cours, notes, exercices et sujets d\'examens partagés',
    'documents.search': 'Rechercher des documents...',
    'documents.filterSubject': 'Filtrer par matière',
    'documents.filterType': 'Filtrer par type',
    'documents.allSubjects': 'Toutes les matières',
    'documents.allTypes': 'Tous les types',
    'documents.showing': 'Affichage de',
    'documents.of': 'sur',
    'documents.documentsText': 'documents',
    'documents.uploadedBy': 'Téléchargé par',
    'documents.downloads': 'téléchargements',
    'documents.download': 'Télécharger',
    
    // What Docs I Need Page
    'whatDocs.title': 'Quels documents ai-je besoin?',
    'whatDocs.subtitle': 'Guide complet des documents requis pour diverses procédures administratives',
    'whatDocs.processingTime': 'Délai de traitement:',
    'whatDocs.requiredDocs': 'Documents requis:',
    'whatDocs.downloadTemplate': 'Télécharger',
    'whatDocs.generalTips': 'Conseils généraux',
    'whatDocs.searchDocs': 'Rechercher des documents...',
    
    // Reclamation Page
    'reclamation.title': 'Soumettre une réclamation',
    'reclamation.subtitle': 'Vous avez un problème ou une préoccupation? Faites-le nous savoir et nous vous aiderons à le résoudre',
    'reclamation.success': 'Votre réclamation a été soumise avec succès! Notre équipe d\'assistance l\'examinera dans les 24 à 48 heures.',
    'reclamation.category': 'Catégorie',
    'reclamation.selectCategory': 'Sélectionner une catégorie',
    'reclamation.subject': 'Sujet',
    'reclamation.subjectPlaceholder': 'Résumé bref de votre problème',
    'reclamation.description': 'Description',
    'reclamation.descriptionPlaceholder': 'Veuillez fournir des informations détaillées sur votre réclamation...',
    'reclamation.descriptionHelp': 'Soyez aussi précis que possible pour nous aider à résoudre votre problème rapidement',
    'reclamation.yourEmail': 'Votre email',
    'reclamation.emailPlaceholder': 'votre.email@universite.ma',
    'reclamation.attachment': 'Pièce jointe (optionnel)',
    'reclamation.uploadFile': 'Cliquez pour télécharger un fichier (PDF, Image ou Document)',
    'reclamation.responseTime': 'Remarque: Le délai de réponse est généralement de 24 à 48 heures. Pour les questions urgentes, veuillez vous rendre directement au bureau des affaires étudiantes.',
    'reclamation.submit': 'Soumettre la réclamation',
    'reclamation.emailSupport': 'Support par email',
    'reclamation.forGeneralInquiries': 'Pour les demandes générales',
    
    // Chat Panel
    'chat.messages': 'Messages',
    'chat.searchMessages': 'Rechercher des messages...',
    'chat.online': 'En ligne',
    'chat.typeMessage': 'Tapez un message...',
    
    // Common
    'common.all': 'Tout',
    
    // Profile Page
    'profile.title': 'Mon profil',
    'profile.editProfile': 'Modifier le profil',
    'profile.fullName': 'Nom complet',
    'profile.email': 'Email',
    'profile.university': 'Université',
    'profile.city': 'Ville',
    'profile.bio': 'Biographie',
    'profile.joinedDate': 'Inscrit',
    'profile.myPosts': 'Mes publications',
    'profile.myServices': 'Mes services',
    'profile.myProducts': 'Mes produits',
    'profile.saveChanges': 'Enregistrer les modifications',
  },
  ar: {
    // Navigation
    'nav.dashboard': 'لوحة القيادة',
    'nav.services': 'الخدمات',
    'nav.products': 'المنتجات',
    'nav.documents': 'الوثائق',
    'nav.whatDocs': 'شنو الوثائق لي خصني؟',
    'nav.reclamation': 'الشكاية',
    'nav.logout': 'خروج',
    'nav.studentNetwork': 'شبكة الطلاب',
    'nav.profile': 'الملف الشخصي',
    
    // Login Page
    'login.title': 'ستوشيال',
    'login.subtitle': 'المنصة الاجتماعية الأولى للطلاب الجامعيين المغاربة',
    'login.welcomeBack': 'مرحبا بعودتك!',
    'login.signInMessage': 'سجل الدخول باش تتواصل مع الطلاب فالمغرب كامل',
    'login.email': 'البريد الجامعي',
    'login.password': 'كلمة السر',
    'login.rememberMe': 'تذكرني',
    'login.forgotPassword': 'نسيتي كلمة السر؟',
    'login.signIn': 'دخول',
    'login.noAccount': 'ماعندكش حساب؟',
    'login.register': 'سجل من هنا',
    'login.footer': '© 2025 ستوشيال. للطلاب الجامعيين المغاربة.',
    
    // Dashboard
    'dashboard.trending': 'الترندينغ دابا',
    'dashboard.whatsMind': 'شنو كاين فبالك؟',
    'dashboard.addImage': 'زيد رابط الصورة (اختياري)',
    'dashboard.post': 'نشر',
    'dashboard.share': 'شارك',
    'dashboard.sharePost': 'شارك المنشور',
    'dashboard.shareWithFriends': 'شارك مع الأصدقاء',
    'dashboard.copyLink': 'نسخ الرابط',
    'dashboard.writeComment': 'كتب تعليق...',
    'dashboard.justNow': 'دابا',
    'dashboard.createPost': 'أنشئ منشور',
    'dashboard.writePost': 'كتب المنشور ديالك...',
    'dashboard.uploadImage': 'رفع صورة',
    'dashboard.publish': 'نشر',
    'dashboard.delete': 'حذف',
    'dashboard.cancel': 'إلغاء',
    'dashboard.hideMessages': 'خبي الرسائل',
    'dashboard.showMessages': 'بين الرسائل',
    'dashboard.publishComment': 'نشر',
    'dashboard.selectFriend': 'اختار صاحب باش تشارك معاه',
    
    // Services Page
    'services.title': 'خدمات الطلاب',
    'services.subtitle': 'اكتشف الخدمات لي كيقدموها زملاءك باش يعاونوك فالدراسة',
    'services.filterServices': 'فلتر الخدمات',
    'services.university': 'الجامعة',
    'services.city': 'المدينة',
    'services.allUniversities': 'كل الجامعات',
    'services.allCities': 'كل المدن',
    'services.showing': 'كنعرض',
    'services.of': 'من',
    'services.servicesText': 'خدمات',
    'services.reviews': 'تقييمات',
    'services.comment': 'علق',
    'services.chat': 'دردش',
    'services.chatWith': 'دردش مع',
    'services.typeMessage': 'كتب الرسالة ديالك هنا...',
    'services.sendMessage': 'صيفط الرسالة',
    'services.addService': 'زيد خدمة',
    'services.title': 'عنوان الخدمة',
    'services.description': 'وصف الخدمة',
    'services.images': 'صور الخدمة',
    'services.price': 'الثمن',
    'services.category': 'الفئة',
    'services.portfolio': 'رابط البورتفوليو',
    'services.skills': 'المهارات (اختياري)',
    'services.experience': 'سنوات الخبرة (اختياري)',
    'services.projects': 'عدد المشاريع (اختياري)',
    'services.publishService': 'نشر الخدمة',
    'services.rating': 'التقييم',
    'services.writeReview': 'كتب رأيك...',
    'services.submitReview': 'قدم الرأي',
    'services.viewReviews': 'شوف الآراء',
    'services.rateService': 'قيم الخدمة',
    
    // Products Page
    'products.title': 'المنتجات الأكاديمية',
    'products.subtitle': 'تصفح المواد والملاحظات والموارد لي شاركوها الطلاب',
    'products.filterProducts': 'فلتر المنتجات',
    'products.showing': 'كنعرض',
    'products.of': 'من',
    'products.productsText': 'منتجات',
    'products.viewDetails': 'شوف التفاصيل',
    'products.description': 'الوصف',
    'products.seller': 'البائع',
    'products.views': 'المشاهدات',
    'products.contactSeller': 'تواصل مع البائع',
    'products.addYourProduct': 'زيد المنتج ديالك',
    'products.addProduct': 'زيد منتج',
    'products.productTitle': 'عنوان المنتج',
    'products.productDescription': 'وصف المنتج',
    'products.price': 'الثمن',
    'products.category': 'الفئة',
    'products.condition': 'الحالة',
    'products.imageUrl': 'رابط الصورة',
    'products.publish': 'نشر المنتج',
    'products.selectCategory': 'اختار الفئة',
    'products.selectCondition': 'اختار الحالة',
    'products.likeNew': 'جديد',
    'products.used': 'مستعمل - حالة جيدة',
    'products.digital': 'رقمي',
    
    // Documents Page
    'documents.title': 'مكتبة الوثائق',
    'documents.subtitle': 'الدخول للدروس والملاحظات والتمارين والامتحانات',
    'documents.search': 'قلب على الوثائق...',
    'documents.filterSubject': 'فلتر حسب المادة',
    'documents.filterType': 'فلتر حسب النوع',
    'documents.allSubjects': 'كل المواد',
    'documents.allTypes': 'كل الأنواع',
    'documents.showing': 'كنعرض',
    'documents.of': 'من',
    'documents.documentsText': 'وثائق',
    'documents.uploadedBy': 'رفعها',
    'documents.downloads': 'تحميلات',
    'documents.download': 'حمل',
    
    // What Docs I Need Page
    'whatDocs.title': 'شنو الوثائق لي خصني؟',
    'whatDocs.subtitle': 'دليل كامل للوثائق المطلوبة للإجراءات الإدارية',
    'whatDocs.processingTime': 'وقت المعالجة:',
    'whatDocs.requiredDocs': 'الوثائق المطلوبة:',
    'whatDocs.downloadTemplate': 'حمل',
    'whatDocs.generalTips': 'نصائح عامة',
    'whatDocs.searchDocs': 'قلب على الوثائق...',
    
    // Reclamation Page
    'reclamation.title': 'قدم شكاية',
    'reclamation.subtitle': 'عندك مشكل ولا استفسار؟ قولنا ونعاونوك',
    'reclamation.success': 'تم تقديم الشكاية بنجاح! الفريق ديالنا غادي يراجعها خلال 24-48 ساعة.',
    'reclamation.category': 'الفئة',
    'reclamation.selectCategory': 'اختار فئة',
    'reclamation.subject': 'الموضوع',
    'reclamation.subjectPlaceholder': 'ملخص قير على المشكل',
    'reclamation.description': 'الوصف',
    'reclamation.descriptionPlaceholder': 'عطينا معلومات تفصيلية على الشكاية...',
    'reclamation.descriptionHelp': 'كون دقيق باش نقدرو نحلو المشكل بسرعة',
    'reclamation.yourEmail': 'البريد ديالك',
    'reclamation.emailPlaceholder': 'email.dyalk@university.ma',
    'reclamation.attachment': 'ملف مرفق (اختياري)',
    'reclamation.uploadFile': 'كليكي باش ترفع ملف (PDF, صورة, ولا وثيقة)',
    'reclamation.responseTime': 'ملاحظة: وقت الرد عادة 24-48 ساعة. للأمور المستعجلة، زور مكتب شؤون الطلاب مباشرة.',
    'reclamation.submit': 'قدم الشكاية',
    'reclamation.emailSupport': 'الدعم بالبريد',
    'reclamation.forGeneralInquiries': 'للاستفسارات العامة',
    
    // Chat Panel
    'chat.messages': 'الرسائل',
    'chat.searchMessages': 'قلب على الرسائل...',
    'chat.online': 'متصل',
    'chat.typeMessage': 'كتب رسالة...',
    
    // Common
    'common.all': 'الكل',
    
    // Profile Page
    'profile.title': 'الملف الشخصي ديالي',
    'profile.editProfile': 'عدل الملف',
    'profile.fullName': 'الاسم الكامل',
    'profile.email': 'البريد الإلكتروني',
    'profile.university': 'الجامعة',
    'profile.city': 'المدينة',
    'profile.bio': 'نبذة',
    'profile.joinedDate': 'انضم في',
    'profile.myPosts': 'منشوراتي',
    'profile.myServices': 'خدماتي',
    'profile.myProducts': 'منتجاتي',
    'profile.saveChanges': 'حفظ التغييرات',
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

